---

apiVersion: v1
kind: Pod
metadata:
  name: meditate
  labels:
    name: meditate
spec:
  containers:
  - name: meditate
    image: europe-west2-docker.pkg.dev/karthick-dev-301823/karthick-dt-dev/meditate
    resources:
      limits:
        memory: "75Mi"
        cpu: "50m"
    ports:
    - containerPort: 80
